Untitled Pull Request
hiroakissh/beginnerasApp pull request #10
Opened 2021-12-22 06:43 UTC by iyu210

レビューお願いします。

2021-12-24 10:47 UTC, hiroyuki0402 commented
> レビューお願いします。
> 
自分の方は明日25に確認してみます。
ただコンフリーク起きてるみたいですね。。。

2021-12-25 04:03 UTC, hiroyuki0402 requested changes
自分なりですが見てみました。
コメント入れてみました。
また、僕の方でも確認して見ますが
コンフリクトに関しては確認をお願いします。

2022-01-04 10:11 UTC, iyu210 commented on beginnerasApp/View/Base.lproj/Main.storyboard
> +        <!--Login View Controller-->
失礼しました。
無くなったと思ってMainに作り直してしまいました。

修正いたします。

2022-01-04 10:12 UTC, iyu210 commented on beginnerasApp/Controller/TabBarController.swift
> +        if Auth.auth().currentUser == nil {
ありがとうございます。

修正いたします。

2022-01-04 10:14 UTC, iyu210 commented on beginnerasApp/Controller/AuthOptionsViewController.swift
> +    @IBOutlet weak private var titleLabel: UILabel!
恥ずかしながらviewDidLoadでしか設定できないと思っていました。

どのタイミングで設定すれば良いでしょうか？

2022-01-04 13:33 UTC, hiroyuki0402 commented on beginnerasApp/Controller/TabBarController.swift
> +        let loginViewController = self.storyboard?.instantiateViewController(withIdentifier: "Login")
guard let loginViewController = self.storyboard?.instantiateViewController(withIdentifier: "Login") else { return }
・・・
self.present(loginViewController, animated: true, completion: nil)
!はなるべく使わないようにしましょう。

2022-01-04 13:33 UTC, hiroyuki0402 commented on beginnerasApp/Controller/LoginViewController.swift
> +        mailTextField.attributedPlaceholder = NSAttributedString(string: "mail address", attributes: [NSAttributedString.Key.foregroundColor : UIColor.white])
拡張使うとかどうですかね。
自分もこんな使い方して良いかわからないですが、
例えば別ファイルかクラスの外で、

extension NSAttributedString {
    func XXXX(xxx: String, ooo: UIColor) -> NSAttributedString {
        let attributedString = NSAttributedString(string: xxx, attributes: [NSAttributedString.Key.foregroundColor : ooo])
        return attributedString
    }
}
作って使うみたいな感じでどうですかね。
使う時は例えば、
@IBOutlet weak private var passwordTextField: UITextField! {
didSet {
passwordTextField. attributedPlaceholder = NSAttributedString().XXXX(xxx: "Test", ooo: .brown)
}
}
などなど。。。。

2022-01-05 13:03 UTC, hiroyuki0402 commented on beginnerasApp/Controller/TabBarController.swift
> +        guard let _ = Auth.auth().currentUser else{
※下記書いたつもりが消えてたのでもう一回書きます。

すみません。自分が勘違いしていました。
guard let ではなく if letと思っていましたが、ドキュメント通りでいいかもしれません。
if let　にしたかったのはemailを取得するとか・・とは思っていましたが、考えてみれば必要ないですね。
これはログイン判断する為のものですよね？
もしくはAuth.auth().currentUser != nil ? 処理A : 処理Bか・・
可読性的に良くないですかね・・・

以下はemailとか取得のイメージしていたものです。
ログイン判断であれば取得する意味なかったです。

if let currentUser = Auth.auth().currentUser {
let email = currentUser.email
画面遷移
}


それからログイン判断はSceneDelegatedeでやるのはどうでしょうか。
Auth.auth().currentUser != nil {  ログインしていたら画面への遷移処理　} else {  していなかったら画面へ遷移の処理 }

アプリ起動時に一番最初に呼ばれるメソッドなのがUISceneSession
みたいです。
SceneDelegateのwillConnectToの中で記述なんてどうですか？
ただ自分は、SceneDelegatedeは詳しくないのでやっても良いのかわからないですし、
画面遷移の時に必要な処理がありそうです。

2022-01-16 14:15 UTC, closed without merging